plugins {
    id 'java'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)  // 设置 JDK 版本
    }
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

tasks.register("compileNative", Exec) {
    def javaHome = System.getenv("JAVA_HOME")
    def outDir = layout.buildDirectory.dir("native").get().asFile
    outDir.mkdirs()

    def outFile = new File(outDir, "lpcNatives.dll")

    workingDir = file("src/main/c")

    commandLine "gcc",
            "-shared",
            "-fPIC",
            "-I${javaHome}/include",
            "-I${javaHome}/include/win32",
            "main.c",
            "-o",
            outFile
}

// ✅ 必须放这里（关键修复）
tasks.compileJava.dependsOn compileNative

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'com.google.code.gson:gson:2.8.9'
    implementation 'org.joml:joml:1.10.5'
    implementation "org.jetbrains:annotations:24.0.1"
    implementation 'it.unimi.dsi:fastutil:8.5.12'
    implementation 'org.apache.logging.log4j:log4j-api:2.23.1'
    implementation 'org.apache.logging.log4j:log4j-core:2.25.4'
    implementation 'com.github.wendykierp:JTransforms:3.1'
    implementation 'org.joml:joml:1.10.4'
    implementation 'net.java.dev.jna:jna:5.13.0'
}

test {
    useJUnitPlatform()
}